export const enum ACTION_TYPES_CONSTANTS {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  SAVE_USER = "SAVE_USER",
  SIGNOUT_USER = "SIGNOUT_USER",
  CHANGE_QUANTITY = "CHANGE_QUANTITY",
  SET_MY_ORDERS = "SET_MY_ORDERS",
}
